version: '3.7'

services:

  php-8.0:
    build: ./.docker/php-8.0
    image: ids_php_8.0
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-8.1:
    build: ./.docker/php-8.1
    image: ids_php_8.1
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
