services:

  php-8.3:
    image: ghcr.io/digital-craftsman-de/ids-php-8.3
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-8.4:
    image: ghcr.io/digital-craftsman-de/ids-php-8.4
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
