version: '3.7'

services:

  php-8.2:
    build: ./.docker/php-8.2
    image: ids_php_8.2
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-8.3:
    build: ./.docker/php-8.3
    image: ids_php_8.3
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
