services:

  DigitalCraftsman\Ids\Serializer\IdNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\Ids\Serializer\IdListNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]

  DigitalCraftsman\Ids\Serializer\MutableIdListNormalizer:
    tags: [ { name: 'serializer.normalizer' } ]
